name: SignSellXSOAP
main: xsoapsell\economysell\EconomySell
version: "1.0.0"
api: [3.0.0, 4.0.0, 4.2.5]
author: xSoapers 
website: https://github.com/xSoapers
depend: [EconomyAPI]

permissions:
 economysell.*:
  description: Includes all permission for EconomySell
  children:
   economysell.sell.*:
    description: Includes all permission related to managing sell center
    children:
     economysell.sell.sell:
      description: Allows player to sell items
      default: true
     economysell.sell.create:
      description: Allows player to create sell center
     economysell.sell.remove:
      description: Allows player to remove sell center

